from tkinter import *
import sqlite3
db=sqlite3.connect('test1.db')
c=db.cursor()
root=Tk()
btn1=StringVar()
def Curselect():
    name=str(l3.get())
    print(name)
    age=l5.get(l5.curselection())
    print(age)
    gender=(btn1.get())
    print(gender)
    address=str(l12.get())
    print(address)
    course=l14.get(l14.curselection())
    print(course)
    sem=l16.get(l16.curselection())
    print(sem)
    try:
        c.execute('CREATE TABLE IF NOT EXISTS students(Name TEXT,Age GPType,Gender GPType,Address TEXT,Course GPType,Semester GPType)')
        c.execute('INSERT INTO students(Name,Age,Gender,Address,Course,Semester)VALUES(?,?,?,?,?,?)',(name,age,gender,address,course,sem))
        db.commit()
        print("Data saved")
    except sqlite3.ProgrammingError as e:
        print(e)
l1=Label(root,text="Student Details")
l1.grid(row=0,column=0)
l2=Label(root,text="NAME :")
l2.grid(row=1,column=0)
l3=Entry(root,text="")
l3.grid(row=1,column=1)
l4=Label(root,text="AGE : ")
l4.grid(row=2,column=0)
l5=Listbox(root,width=5,height=1,selectmode=SINGLE,exportselection=0)
for i in range(0,100):
    l5.insert(END,i)
    
l5.grid(row=2,column=1)
l6=Scrollbar(root,width=10)
l5.configure(yscrollcommand=l6.set)
l6.configure(command=l5.yview)
l6.grid(row=2,column=2)
l7=Label(root,text="Gender :")
l7.grid(row=4,column=0)
l8=Radiobutton(root,text="Male",value="MALE",variable=btn1)
l8.grid(row=4,column=1)
l9=Radiobutton(root,text="Female",value="FEMALE",variable=btn1)
l9.grid(row=4,column=2)
l10=Label(root,text="Address : ")
l10.grid(row=5,column=0)
l12=Entry(root,text="",width=30)
l12.grid(row=5,column=1)
l13=Label(root,text="Course :")
l13.grid(row=6,column=0)
L=['CSE','ME','CE','ECE','B.COM','B.Sc','MBA']
l14=Listbox(root,width=12,height=1,selectmode=SINGLE,exportselection=0)
for item in L:
    l14.insert(END,item)
    
l14.grid(row=6,column=1)
l15=Scrollbar(root,width=10)
l14.configure(yscrollcommand=l15.set)
l15.configure(command=l14.yview)
l15.grid(row=6,column=2)
l18=Label(root,text="Semester :")
l18.grid(row=8,column=0)
l16=Listbox(root,width=12,height=1,selectmode=SINGLE,exportselection=0)
for j in range(1,9):
    l16.insert(END,j)
l16.grid(row=8,column=1)
l17=Scrollbar(root,width=10)
l16.configure(yscrollcommand=l17.set)
l17.configure(command=l16.yview)
l17.grid(row=8,column=2)
b1=Button(root,text="Save",command=Curselect)
b1.grid(row=10,column=1)
root.mainloop()
